# Generated by Django 5.0.6 on 2024-05-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens/')),
            ],
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='imagens',
            field=models.ManyToManyField(blank=True, to='core.imagem'),
        ),
    ]
