# Generated by Django 5.0.6 on 2024-05-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagem_ocorrencia_imagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='especie',
            field=models.CharField(choices=[('CS', 'Coral Sol'), ('PL', 'Peixe Leão')], default='CS', max_length=2),
        ),
    ]
